# Generated by Django 4.2.7 on 2023-11-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_contact',
            new_name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='color',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='initials',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
