# Generated by Django 4.2.7 on 2023-12-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0002_rename_user_contact_customuser_email_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=50)),
                ('descriptioon', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='videos')),
            ],
        ),
    ]
