# Generated by Django 4.2.7 on 2023-12-03 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0003_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='titel',
            new_name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
