# Generated by Django 4.2.7 on 2024-02-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0004_video_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_size',
            field=models.CharField(blank=True, default=0, null=True),
        ),
    ]
