# Generated by Django 4.2.7 on 2023-12-03 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0005_alter_video_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 23, 23, 4, 387753, tzinfo=datetime.timezone.utc)),
        ),
    ]
