# Generated by Django 4.2.7 on 2023-12-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0010_remove_video_thumbnail_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='chat',
            new_name='video',
        ),
    ]
