# Generated by Django 4.2.7 on 2023-12-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0011_rename_chat_thumbnail_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
