# Generated by Django 4.2.7 on 2023-12-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0012_thumbnail_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
