# Generated by Django 4.2.7 on 2023-12-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0014_video_file_480p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='descriptioon',
            new_name='description',
        ),
    ]
