# Generated by Django 4.2.7 on 2023-12-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0015_rename_descriptioon_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_480p',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
