# Generated by Django 4.2.7 on 2023-12-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0017_alter_video_file_480p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_480p',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
