# Generated by Django 4.2.7 on 2024-02-23 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0017_alter_video_file_480p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file_480p',
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='watchlist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails'),
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
